# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Generate all Numworks Apps 

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 1 * *'
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CPY: './copydir'
  MAKEFLAGS: ${{ (github.repository == 'twingsister/epsilon-internal') && '-j32' || '-j2' }}

jobs:
   bailout:
      runs-on: ubuntu-latest
      steps :
      - name: bail out
      #if:  steps.lastrelease.outputs.TAGNAME == steps.ggb.outputs.tag 
      - run: exit 1
    #   - name: stop
 #     uses: mxschmitt/action-tmate@v3   
