
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 1 * *'
    # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  CPY: './copydir'
  MAKEFLAGS: ${{ (github.repository == 'twingsister/epsilon-internal') && '-j32' || '-j2' }}

jobs:
   bailout:
      runs-on: ubuntu-latest
      steps :
      - name: bail out
      - run: exit 1
    #   - name: stop
 #     uses: mxschmitt/action-tmate@v3   
